# This is a configuration file for twee-tools.
# For information on that project, visit: 
# For information about the TOML file format for this config file, see: https://toml.io/en/


# By default, an HTML file with the name of the story will be generated in the directory
# above the config.toml.
# output = "path/to/file.html"

# The stylesheet files. By default only story.css.
style = ["story.css"]

# The story script files. By default only story.js.
script = ["story.js"]

# The .twee files that will be build. true signifies that all .twee files and in all subdirectories should be used.
twee_files = true

# In this form, only first.twee and second.twee would be included.
# twee_files = ["first.twee", "second.twee"]




